# Generated by Django 4.2.7 on 2024-03-15 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_product_final_price_alter_product_seller'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='categories',
        ),
    ]
