# Generated by Django 4.2.7 on 2023-12-10 20:14

import apps.membership.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0006_alter_customermembership_status'),
        ('accounts', '0007_alter_customer_membership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='membership',
            field=models.OneToOneField(blank=True, default=apps.membership.models.CustomerMembership.default_object, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='membership.customermembership'),
        ),
    ]
