# Generated by Django 4.2.7 on 2024-03-15 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_comment_likes_alter_comment_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='category',
            new_name='categories',
        ),
    ]
