# Generated by Django 4.2.7 on 2023-12-05 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0005_customermembership_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermembership',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=155),
        ),
    ]
