# Generated by Django 4.2.7 on 2023-12-12 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0006_alter_customermembership_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customermembership',
            old_name='membership',
            new_name='model',
        ),
    ]
