# Generated by Django 4.2.7 on 2024-01-18 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0007_rename_membership_customermembership_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermembership',
            name='start_date',
            field=models.DateField(),
        ),
    ]
