# Generated by Django 4.2.7 on 2024-01-18 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0009_alter_customermembership_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermembership',
            name='start_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
    ]
