# Generated by Django 4.2.7 on 2024-02-19 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0012_membership_final_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='final_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='membership',
            name='unit_price',
            field=models.FloatField(),
        ),
    ]
