# Generated by Django 4.2.7 on 2023-12-09 00:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('accounts', '0004_alter_customer_membership_alter_customer_reputation'),
        ('ecommerce', '0002_alter_clothes_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer')),
                ('items', models.ManyToManyField(to='orders.orderitem')),
            ],
        ),
    ]
