# Generated by Django 4.2.7 on 2023-11-16 16:44

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('discount', models.FloatField(blank=True, default=0.0, null=True)),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=50)),
                ('level', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(3)])),
                ('desc', models.TextField()),
                ('duration', models.DurationField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
