# Generated by Django 4.2.7 on 2023-11-20 16:46

import apps.membership.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_alter_membership_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='level',
            field=models.PositiveIntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='membership',
            name='slug',
            field=models.SlugField(blank=True, editable=False),
        ),
        migrations.CreateModel(
            name='CustomerMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(blank=True)),
                ('membership', models.ForeignKey(default=apps.membership.models.Membership.default_object, null=True, on_delete=django.db.models.deletion.SET_NULL, to='membership.membership')),
            ],
        ),
    ]
