# Generated by Django 4.2.7 on 2024-03-04 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_alter_customermembership_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='final_price',
            field=models.FloatField(blank=True),
        ),
    ]
