# Generated by Django 4.2.7 on 2024-03-11 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_alter_membership_final_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customermembership',
            old_name='customer',
            new_name='user',
        ),
    ]
