# Generated by Django 4.2.7 on 2023-11-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0004_alter_customermembership_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermembership',
            name='status',
            field=models.CharField(choices=[('AC', 'Active'), ('SU', 'Suspended')], default='AC', max_length=155),
        ),
    ]
