# Generated by Django 4.2.7 on 2024-02-19 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0011_alter_customermembership_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
