# Generated by Django 4.2.7 on 2024-02-19 20:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0013_alter_membership_final_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='discount',
            field=models.PositiveSmallIntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
