# Generated by Django 4.2.7 on 2024-02-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0014_alter_membership_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='final_price',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='unit_price',
            field=models.FloatField(blank=True),
        ),
    ]
