# Generated by Django 4.2.7 on 2024-02-21 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0015_alter_membership_final_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='final_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='membership',
            name='unit_price',
            field=models.FloatField(),
        ),
    ]
