# Generated by Django 4.2.7 on 2024-02-26 18:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_product_category_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rate',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
    ]
