# Generated by Django 4.2.7 on 2023-11-25 16:04

import apps.special_orders.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ecommerce', '0001_initial'),
        ('accounts', '0004_alter_customer_membership_alter_customer_reputation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sketch', models.ImageField(blank=True, null=True, upload_to=apps.special_orders.models.sp_loc)),
                ('text', models.TextField(help_text='<p>Here you gotta specify your ideas</p>')),
                ('material', models.CharField(choices=[('PL', 'polyester'), ('CT', 'cotton')], max_length=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_orders', to='accounts.customer')),
                ('type_of_clothes', models.ManyToManyField(to='ecommerce.clothes')),
            ],
        ),
    ]
