# Generated by Django 4.2.7 on 2023-11-20 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_alter_membership_duration_alter_membership_level_and_more'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.customermembership'),
        ),
    ]
