# Generated by Django 4.2.7 on 2023-11-20 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0004_alter_customermembership_end_date'),
        ('accounts', '0002_alter_customer_membership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='membership',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='membership.customermembership'),
        ),
    ]
