# Generated by Django 4.2.7 on 2023-11-25 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clothes',
            options={'verbose_name_plural': 'Clothes'},
        ),
    ]
